# Generated by Django 4.0.6 on 2022-07-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=20)),
                ('TransactionType', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
